[versions]
appcompat = "1.6.1"
coreKtx = "1.13.1"
dicioNumbers = "dummy-SNAPSHOT"
gradle = "8.4.0"
junit = "4.13.2"
kotlinGradlePlugin = "1.9.24"


[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
dicio-numbers = { module = "com.github.Stypox:dicio-numbers", version.ref = "dicioNumbers" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }

[plugins]
