[versions]
appcompat = "1.6.1"
coreKtx = "1.13.1"
dicioNumbers = "dummy-2"
gradle = "8.4.0"
junit = "4.13.2"
kotlin = "1.9.24"


[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
dicio-numbers = { module = "com.github.Stypox:dicio-numbers", version.ref = "dicioNumbers" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
com-android-library = { id = "com.android.library", version.ref = "gradle" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
